version: "3.1"

services:
  #This handles all of the http request to simple cert issues and both the SP and IdP can share the same ports.
  httpd-proxy:
    build: ./httpd-proxy/
    networks:
     - back
    ports:
     - "80:80"
     - "443:443"

  sp:
    build: ./sp/ 
    networks:
     - back
    secrets:
     - source: sp_key

networks:
  back:    
    driver: bridge

secrets:
  sp_key:
    file: ./secrets/sp/sp-key.pem
